version: "3.8"

services:
  php-crud:
    build:
      context: ./php-crud
      target: prod
    ports:
      - "${APP_PORT}:80"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - db

  db:
    image: mariadb:10.7
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    volumes:
      - ./db/script_inicial.sql:/docker-entrypoint-initdb.d/init.sql
      - prod-db-data:/var/lib/mysql

volumes:
  prod-db-data:
